# Generated by Django 5.0.2 on 2024-02-18 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0004_user_isdeletecustomer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryid', models.AutoField(primary_key=True, serialize=False)),
                ('categoryname', models.CharField(max_length=255)),
                ('categoryunit', models.CharField(choices=[('Pcs', 'Pieces'), ('doz', 'Dozones'), ('ctn', 'Carton'), ('kg', 'Kilogram'), ('g', 'gram'), ('MT', 'Metric Ton'), ('oz', 'Ounce'), ('t', 'Ton'), ('lb', 'Pound'), ('l', 'Liter'), ('ml', 'Milliliter'), ('m', 'Meter'), ('sqm', 'Square Meter'), ('cbm', 'Cubic Meter')], max_length=50)),
                ('companyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company')),
            ],
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('legalidno', models.CharField(default='', max_length=255, primary_key=True, serialize=False)),
                ('companyname', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=255)),
                ('contactperson_fname', models.CharField(max_length=255)),
                ('contactperson_lname', models.CharField(max_length=255)),
                ('contactperson_contact', models.CharField(max_length=255)),
                ('contactperson_email', models.CharField(max_length=255)),
                ('companyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('barcode', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('mfgdate', models.DateField()),
                ('expirydate', models.DateField()),
                ('costprice', models.FloatField()),
                ('sellingprice', models.FloatField()),
                ('mrp', models.FloatField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_stock', to='dealer.category')),
                ('companyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company')),
                ('dealer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dealer.dealer')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_stock', to='dealer.category')),
            ],
        ),
    ]
