# Generated by Django 5.0.2 on 2024-02-17 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=20)),
                ('lat', models.CharField(max_length=100)),
                ('long', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('email', models.CharField(default='', max_length=255, primary_key=True, serialize=False)),
                ('companyname', models.CharField(default='', max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=20)),
                ('lat', models.CharField(max_length=100)),
                ('long', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('subscription_id', models.AutoField(primary_key=True, serialize=False)),
                ('subscription_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=2000)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=255, null=True)),
                ('lname', models.CharField(max_length=255, null=True)),
                ('iscmpid', models.BooleanField(default=False)),
                ('isbraid', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_billing_clerk', models.BooleanField(default=False)),
                ('isaddbranch', models.BooleanField(default=False)),
                ('iseditbranch', models.BooleanField(default=False)),
                ('isviewbranch', models.BooleanField(default=False)),
                ('isdeletebranch', models.BooleanField(default=False)),
                ('isadduser', models.BooleanField(default=False)),
                ('isdeleteuser', models.BooleanField(default=False)),
                ('isedituser', models.BooleanField(default=False)),
                ('isviewuser', models.BooleanField(default=False)),
                ('isaddstock', models.BooleanField(default=False)),
                ('iseditstock', models.BooleanField(default=False)),
                ('iseviewstock', models.BooleanField(default=False)),
                ('isedeletestock', models.BooleanField(default=False)),
                ('isaddcustomer', models.BooleanField(default=False)),
                ('isdeletecompany', models.BooleanField(default=False)),
                ('istakeattendance', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('branchid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.branch')),
                ('companyid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='account.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company'),
        ),
        migrations.CreateModel(
            name='attandance',
            fields=[
                ('attandance_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('ipaddress', models.CharField(blank=True, max_length=45, null=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.branch')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company')),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.IntegerField()),
                ('generatedtime', models.DateTimeField()),
                ('used', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription_purchase',
            fields=[
                ('purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_date', models.DateTimeField()),
                ('expiry_date', models.DateTimeField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company')),
                ('subscription_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.subscription')),
            ],
        ),
    ]
