# Generated by Django 5.0.2 on 2024-02-08 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('subscription_id', models.AutoField(primary_key=True, serialize=False)),
                ('subscription_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=2000)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='companyid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.company'),
        ),
    ]
