# Generated by Django 5.0.2 on 2024-02-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='id',
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.CharField(default='', max_length=255, primary_key=True, serialize=False),
        ),
    ]
