# Generated by Django 5.0.2 on 2024-02-08 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_subscription_alter_user_companyid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription_purchase',
            fields=[
                ('purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_date', models.DateTimeField()),
                ('expiry_date', models.DateTimeField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company')),
                ('subscription_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.subscription')),
            ],
        ),
    ]
