# Generated by Django 5.0.2 on 2024-02-10 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_company_id_company_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='companyid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.company'),
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=20)),
                ('lat', models.CharField(max_length=100)),
                ('long', models.CharField(max_length=100)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='branchid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.branch'),
        ),
    ]
