# Generated by Django 5.0.2 on 2024-02-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_companyid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isviewcustomer',
            field=models.BooleanField(default=False),
        ),
    ]
