# Generated by Django 5.0.2 on 2024-02-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_companyid_branch_user_branchid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('subscription_id', models.AutoField(primary_key=True, serialize=False)),
                ('subscription_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=2000)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
