# Generated by Django 4.1.5 on 2024-02-10 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_branch_attandance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branchid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.branch'),
        ),
    ]
