# Generated by Django 5.0.2 on 2024-02-10 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='attandance',
            fields=[
                ('attandance_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.branch')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription_purchase',
            fields=[
                ('purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_date', models.DateTimeField()),
                ('expiry_date', models.DateTimeField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company')),
                ('subscription_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.subscription')),
            ],
        ),
    ]
