# Generated by Django 5.0.2 on 2024-02-10 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
