# Generated by Django 5.0.2 on 2024-02-11 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isbraid',
            field=models.BooleanField(default=False),
        ),
    ]
