# Generated by Django 5.0.2 on 2024-02-11 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_user_isbraid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
