# Generated by Django 5.0.2 on 2024-02-14 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_attandance_ip_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attandance',
            old_name='ip_address',
            new_name='ipaddress',
        ),
    ]
