# Generated by Django 5.0.2 on 2024-02-15 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_rename_ip_address_attandance_ipaddress'),
        ('customer', '0002_remove_customer_address_remove_customer_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='companyid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.company'),
        ),
    ]
